package interfaces;

import classes.Idioma;
import classes.MenuUtil;
import classes.Tradutor;
import classes.Usuario;
import classes.UsuarioLogado;
import javax.swing.Icon;
import javax.swing.JMenuItem;

/**
 *
 * @author ryans
 */
public class TelaInicial extends javax.swing.JFrame {
    private Tradutor tradutor;

    public TelaInicial() {
        initComponents();
        // Obter o usuário logado
        Usuario usuarioLogado = UsuarioLogado.getUsuario();
        // Chamar o método para esconder o menu item se necessário
        esconderMenuItem(usuarioLogado);

        tradutor = new Tradutor(Idioma.getIdiomaAtual()); // Idioma padrão
        atualizarTexto();
        pt_btn.addActionListener(e -> {
            Idioma.setIdiomaAtual("pt");
                    atualizarTexto();
        });

        en_btn.addActionListener(e -> {
            Idioma.setIdiomaAtual("en");
                    atualizarTexto();
        });
         es_btn.addActionListener(e -> {
            Idioma.setIdiomaAtual("es");
                    atualizarTexto();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telalabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        pt_btn = new javax.swing.JMenuItem();
        en_btn = new javax.swing.JMenuItem();
        es_btn = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        cd_menu = new javax.swing.JMenu();
        cdg_btn = new javax.swing.JMenuItem();
        cdm_btn = new javax.swing.JMenuItem();
        gr_btn = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        evsgt_btn = new javax.swing.JMenuItem();
        sgtev_btn = new javax.swing.JMenuItem();
        mysgt_btn = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(625, 383));
        getContentPane().setLayout(null);

        telalabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        telalabel.setForeground(new java.awt.Color(255, 255, 255));
        telalabel.setText("Tela Inicial");
        getContentPane().add(telalabel);
        telalabel.setBounds(220, 40, 190, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/360_F_823155337_DzGKTtbWRgXd5xGV42yLZqRyrX7fLsk0.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 626, 360);

        jMenu1.setText("opções");

        jMenu2.setText("Idioma");

        pt_btn.setText("Português (pt-br)");
        jMenu2.add(pt_btn);

        en_btn.setText("Inglês (en)");
        jMenu2.add(en_btn);

        es_btn.setText("espanhol (es)");
        jMenu2.add(es_btn);

        jMenu1.add(jMenu2);

        jMenuItem1.setText("sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        cd_menu.setText("administração");

        cdg_btn.setText("cadastro Gestão");
        cdg_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdg_btnActionPerformed(evt);
            }
        });
        cd_menu.add(cdg_btn);

        cdm_btn.setText("Cadastro moradores");
        cdm_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdm_btnActionPerformed(evt);
            }
        });
        cd_menu.add(cdm_btn);

        gr_btn.setText("gerenciamento de usuarios");
        gr_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gr_btnActionPerformed(evt);
            }
        });
        cd_menu.add(gr_btn);

        jMenuBar1.add(cd_menu);

        jMenu3.setText("menu Sugestões");

        evsgt_btn.setText("enviar sugestões");
        evsgt_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evsgt_btnActionPerformed(evt);
            }
        });
        jMenu3.add(evsgt_btn);

        sgtev_btn.setText("sugestões gerais");
        sgtev_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sgtev_btnActionPerformed(evt);
            }
        });
        jMenu3.add(sgtev_btn);

        mysgt_btn.setText("minhas sugestões ");
        mysgt_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mysgt_btnActionPerformed(evt);
            }
        });
        jMenu3.add(mysgt_btn);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cdg_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdg_btnActionPerformed
      CadastroGestores cdg = new CadastroGestores(Idioma.getIdiomaAtual());
      cdg.setVisible(true);
      dispose();
    }//GEN-LAST:event_cdg_btnActionPerformed

    private void cdm_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdm_btnActionPerformed
      CadastroUsuario cdm = new CadastroUsuario(Idioma.getIdiomaAtual());
      cdm.setVisible(true);
      dispose();
    }//GEN-LAST:event_cdm_btnActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    UsuarioLogado.logout();
    // Atualizar a interface, talvez escondendo menus ou retornando à tela de login
    System.out.println("Logout realizado com sucesso!");
     dispose();     
     TelaLogin tl = new TelaLogin();
     tl.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void evsgt_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evsgt_btnActionPerformed
     dispose();     
     EnviarSugestoes evs = new EnviarSugestoes();
     evs.setVisible(true);
    }//GEN-LAST:event_evsgt_btnActionPerformed

    private void mysgt_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mysgt_btnActionPerformed
     MinhasSugestões msgt = new MinhasSugestões();
     msgt.setVisible(true);
    }//GEN-LAST:event_mysgt_btnActionPerformed

    private void sgtev_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sgtev_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sgtev_btnActionPerformed

    private void gr_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gr_btnActionPerformed
     GerenciarUsuarios gru = new GerenciarUsuarios();
     gru.setVisible(true);
    }//GEN-LAST:event_gr_btnActionPerformed
    private void esconderMenuItem(Usuario usuarioLogado) {
        if (usuarioLogado != null && !usuarioLogado.getTipo().equals("gerente")) {
            cd_menu.setVisible(false); // Esconde o JMenuItem se não for gerente
            cdg_btn.setVisible(false); // Esconde o JMenuItem se não for gerente
            sgtev_btn.setVisible(false); // Esconde o JMenuItem se não for gerente
            gr_btn.setVisible(false); // Esconde o JMenuItem se não for gerente
        }
    }
    private void mudarIdioma(String idioma) {
        tradutor.setIdiomaAtual(idioma);
        atualizarTexto();
    }

    private void atualizarTexto() {
        telalabel.setText(tradutor.traduzir("bemVindo"));
        jMenu1.setText(tradutor.traduzir("opções"));
        jMenu2.setText(tradutor.traduzir("Idioma"));
        cd_menu.setText(tradutor.traduzir("registro"));
        cdg_btn.setText(tradutor.traduzir("cadastroGestores"));
        cdm_btn.setText(tradutor.traduzir("cadastroUsuario"));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu cd_menu;
    private javax.swing.JMenuItem cdg_btn;
    private javax.swing.JMenuItem cdm_btn;
    private javax.swing.JMenuItem en_btn;
    private javax.swing.JMenuItem es_btn;
    private javax.swing.JMenuItem evsgt_btn;
    private javax.swing.JMenuItem gr_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem mysgt_btn;
    private javax.swing.JMenuItem pt_btn;
    private javax.swing.JMenuItem sgtev_btn;
    private javax.swing.JLabel telalabel;
    // End of variables declaration//GEN-END:variables
}
